// Shared TypeScript types used across the frontend and backend.
// Keeping them in one place means both sides always agree on the shape of data.

// The stages in our processing pipeline, in order
export type StepStatus = "pending" | "active" | "done" | "error";

export interface ProcessingStep {
  id: string;       // unique key, e.g. "download"
  label: string;    // human-readable label shown in the UI
  status: StepStatus;
}

// One viral clip returned by the backend
export interface Clip {
  title: string;        // short title generated by Claude
  reason: string;       // why Claude thinks this is viral
  start_time: number;   // start in seconds
  end_time: number;     // end in seconds
  filename: string;     // the clip file we can serve, e.g. "clip_1.mp4"
}

// Shape of a job returned by /api/status/:jobId
export interface JobState {
  jobId: string;
  status: "pending" | "processing" | "done" | "error";
  steps: ProcessingStep[];
  clips: Clip[];
  error?: string;
}

// The initial set of steps we always start with (all pending)
export const INITIAL_STEPS: ProcessingStep[] = [
  { id: "download",    label: "Downloading video",           status: "pending" },
  { id: "audio",       label: "Extracting audio",            status: "pending" },
  { id: "transcribe",  label: "Transcribing with Whisper",   status: "pending" },
  { id: "analyze",     label: "Analyzing with Claude AI",    status: "pending" },
  { id: "clip",        label: "Cutting viral clips",         status: "pending" },
];
